// flow-typed signature: 2e69e4e72bb02377a569fcaeb5936ace
// flow-typed version: <<STUB>>/@commitlint/config-lerna-scopes_v^8.2.0/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/config-lerna-scopes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/config-lerna-scopes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@commitlint/config-lerna-scopes/index' {
  declare module.exports: $Exports<'@commitlint/config-lerna-scopes'>;
}
declare module '@commitlint/config-lerna-scopes/index.js' {
  declare module.exports: $Exports<'@commitlint/config-lerna-scopes'>;
}
