// flow-typed signature: 631a606f1f524c27310d945d4b89f675
// flow-typed version: <<STUB>>/docma_v^3.2.2/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docma' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docma/bin/commands/serve' {
  declare module.exports: any;
}

declare module 'docma/bin/commands/template.doctor' {
  declare module.exports: any;
}

declare module 'docma/bin/commands/template.init' {
  declare module.exports: any;
}

declare module 'docma/bin/docma' {
  declare module.exports: any;
}

declare module 'docma/lib/_init' {
  declare module.exports: any;
}

declare module 'docma/lib/_init/template/js/app.min' {
  declare module.exports: any;
}

declare module 'docma/lib/Debug' {
  declare module.exports: any;
}

declare module 'docma/lib/Docma' {
  declare module.exports: any;
}

declare module 'docma/lib/HtmlParser' {
  declare module.exports: any;
}

declare module 'docma/lib/Paths' {
  declare module.exports: any;
}

declare module 'docma/lib/Template' {
  declare module.exports: any;
}

declare module 'docma/lib/TemplateBuilder' {
  declare module.exports: any;
}

declare module 'docma/lib/TemplateDoctor' {
  declare module.exports: any;
}

declare module 'docma/lib/utils' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/dust-core' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/dust-core.min' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/dust-helpers' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/dust-helpers.min' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/EventEmitter' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/EventEmitter.min' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/jquery' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/jquery.min' {
  declare module.exports: any;
}

declare module 'docma/lib/web/components/page' {
  declare module.exports: any;
}

declare module 'docma/lib/web/DocmaWeb-filters' {
  declare module.exports: any;
}

declare module 'docma/lib/web/DocmaWeb-SPA' {
  declare module.exports: any;
}

declare module 'docma/lib/web/DocmaWeb' {
  declare module.exports: any;
}

declare module 'docma/lib/web/DocmaWeb.Route' {
  declare module.exports: any;
}

declare module 'docma/lib/web/DocmaWeb.Utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docma/bin/commands/serve.js' {
  declare module.exports: $Exports<'docma/bin/commands/serve'>;
}
declare module 'docma/bin/commands/template.doctor.js' {
  declare module.exports: $Exports<'docma/bin/commands/template.doctor'>;
}
declare module 'docma/bin/commands/template.init.js' {
  declare module.exports: $Exports<'docma/bin/commands/template.init'>;
}
declare module 'docma/bin/docma.js' {
  declare module.exports: $Exports<'docma/bin/docma'>;
}
declare module 'docma/index' {
  declare module.exports: $Exports<'docma'>;
}
declare module 'docma/index.js' {
  declare module.exports: $Exports<'docma'>;
}
declare module 'docma/lib/_init/index' {
  declare module.exports: $Exports<'docma/lib/_init'>;
}
declare module 'docma/lib/_init/index.js' {
  declare module.exports: $Exports<'docma/lib/_init'>;
}
declare module 'docma/lib/_init/template/js/app.min.js' {
  declare module.exports: $Exports<'docma/lib/_init/template/js/app.min'>;
}
declare module 'docma/lib/Debug.js' {
  declare module.exports: $Exports<'docma/lib/Debug'>;
}
declare module 'docma/lib/Docma.js' {
  declare module.exports: $Exports<'docma/lib/Docma'>;
}
declare module 'docma/lib/HtmlParser.js' {
  declare module.exports: $Exports<'docma/lib/HtmlParser'>;
}
declare module 'docma/lib/Paths.js' {
  declare module.exports: $Exports<'docma/lib/Paths'>;
}
declare module 'docma/lib/Template.js' {
  declare module.exports: $Exports<'docma/lib/Template'>;
}
declare module 'docma/lib/TemplateBuilder.js' {
  declare module.exports: $Exports<'docma/lib/TemplateBuilder'>;
}
declare module 'docma/lib/TemplateDoctor.js' {
  declare module.exports: $Exports<'docma/lib/TemplateDoctor'>;
}
declare module 'docma/lib/utils.js' {
  declare module.exports: $Exports<'docma/lib/utils'>;
}
declare module 'docma/lib/web/components/dust-core.js' {
  declare module.exports: $Exports<'docma/lib/web/components/dust-core'>;
}
declare module 'docma/lib/web/components/dust-core.min.js' {
  declare module.exports: $Exports<'docma/lib/web/components/dust-core.min'>;
}
declare module 'docma/lib/web/components/dust-helpers.js' {
  declare module.exports: $Exports<'docma/lib/web/components/dust-helpers'>;
}
declare module 'docma/lib/web/components/dust-helpers.min.js' {
  declare module.exports: $Exports<'docma/lib/web/components/dust-helpers.min'>;
}
declare module 'docma/lib/web/components/EventEmitter.js' {
  declare module.exports: $Exports<'docma/lib/web/components/EventEmitter'>;
}
declare module 'docma/lib/web/components/EventEmitter.min.js' {
  declare module.exports: $Exports<'docma/lib/web/components/EventEmitter.min'>;
}
declare module 'docma/lib/web/components/jquery.js' {
  declare module.exports: $Exports<'docma/lib/web/components/jquery'>;
}
declare module 'docma/lib/web/components/jquery.min.js' {
  declare module.exports: $Exports<'docma/lib/web/components/jquery.min'>;
}
declare module 'docma/lib/web/components/page.js' {
  declare module.exports: $Exports<'docma/lib/web/components/page'>;
}
declare module 'docma/lib/web/DocmaWeb-filters.js' {
  declare module.exports: $Exports<'docma/lib/web/DocmaWeb-filters'>;
}
declare module 'docma/lib/web/DocmaWeb-SPA.js' {
  declare module.exports: $Exports<'docma/lib/web/DocmaWeb-SPA'>;
}
declare module 'docma/lib/web/DocmaWeb.js' {
  declare module.exports: $Exports<'docma/lib/web/DocmaWeb'>;
}
declare module 'docma/lib/web/DocmaWeb.Route.js' {
  declare module.exports: $Exports<'docma/lib/web/DocmaWeb.Route'>;
}
declare module 'docma/lib/web/DocmaWeb.Utils.js' {
  declare module.exports: $Exports<'docma/lib/web/DocmaWeb.Utils'>;
}
