// flow-typed signature: 296ab12f1eb788315c36d7dc13e3651d
// flow-typed version: <<STUB>>/gulp_v^4.0.2/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp/bin/gulp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp/bin/gulp.js' {
  declare module.exports: $Exports<'gulp/bin/gulp'>;
}
declare module 'gulp/index' {
  declare module.exports: $Exports<'gulp'>;
}
declare module 'gulp/index.js' {
  declare module.exports: $Exports<'gulp'>;
}
