// flow-typed signature: 01793396fb4551ca767660807fc40ab0
// flow-typed version: <<STUB>>/gulp-terser_v^1.2.0/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-terser/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-terser/lib/index' {
  declare module.exports: $Exports<'gulp-terser/lib'>;
}
declare module 'gulp-terser/lib/index.js' {
  declare module.exports: $Exports<'gulp-terser/lib'>;
}
